language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"


services: PostgreSQL

before_script:
  - composer install --dev --no-interaction
  - psql -c 'create database openacalendartest;' -U postgres
  - echo "<?php" >> config.test.php
  - echo "\$CONFIG->isDebug = false;" >> config.test.php
  - echo "\$CONFIG->databaseName = 'openacalendartest';" >> config.test.php
  - echo "\$CONFIG->databaseHost = 'localhost';" >> config.test.php
  - echo "\$CONFIG->databaseUser = 'postgres';" >> config.test.php
  - echo "\$CONFIG->databasePassword = '';" >> config.test.php
  - echo "\$CONFIG->extensions = array('CuratedLists');" >> config.test.php

script: phpunit --coverage-clover build/logs/clover.xml  --configuration core/tests/phpunit.xml


after_script:
  - php vendor/satooshi/php-coveralls/composer/bin/coveralls -v



